### ISSUE TITLE
Works in development, but not on production

### ISSUE THREAD

**Issue by glebm** [mreinsch/authlogic_openid#1]
I tried implementing openid with auto_register, and it works fine on development, but I have some really weird messages in the log.

On production machine it doesn't work at all (although it works on the local staging machine).

Here is what I get in the log on development (signing in with a Google openid account):

<pre><code class="ruby">
Processing UserSessionsController#new (for 127.0.0.1 at 2010-03-29 02:29:20) [GET]
  Parameters: {"action"=>"new", "controller"=>"user_sessions"}
  SQL (8.1ms)   SHOW TABLES
  SQL (1.6ms)   SHOW TABLES
  Permission Load (9.2ms)   SELECT * FROM `permissions` WHERE (name = 'Admin') LIMIT 1
  Permission Load (0.6ms)   SELECT * FROM `permissions` WHERE (name = 'Edit Tutorials') LIMIT 1
  Permission Load (2.0ms)   SELECT * FROM `permissions` WHERE (name = 'Edit Blog') LIMIT 1
  Permission Load (4.0ms)   SELECT * FROM `permissions` WHERE (name = 'Delete Comments') LIMIT 1
  Permission Load (2.6ms)   SELECT * FROM `permissions` WHERE (name = 'Browse Stats') LIMIT 1
  Permission Load (0.9ms)   SELECT * FROM `permissions` WHERE (name = 'Full Users Access') LIMIT 1
  Permission Load (9.6ms)   SELECT * FROM `permissions` 
  Permission Columns (2.3ms)   SHOW FIELDS FROM `permissions`
  UserGroup Load (6.6ms)   SELECT * FROM `user_groups` WHERE (name = 'Administrators') LIMIT 1
  UserGroup Columns (5.9ms)   SHOW FIELDS FROM `user_groups`
  permissions_user_groups Columns (6.6ms)   SHOW FIELDS FROM `permissions_user_groups`
  Permission Load (2.0ms)   SELECT * FROM `permissions` INNER JOIN `permissions_user_groups` ON `permissions`.id = `permissions_user_groups`.permission_id WHERE (`permissions_user_groups`.user_group_id = 1 ) 
Rendering template within layouts/application
Rendering user_sessions/new
Rendered shared/_openid_login_form (67.1ms)
Rendered shared/_irequest_login_form (197.1ms)
Rendered shared/_menu (69.0ms)
Rendered shared/_dj_select (41.3ms)
Rendered shared/_footer_menu (154.4ms)
Completed in 3957ms (View: 886, DB: 70) | 200 OK [http://localhost/user_session/new]
=> Requiring Lockdown rules engine: /home/gleb/projects/iRequest/iRequest-Web/lib/lockdown/init.rb 

  SQL (0.8ms)   SET NAMES 'utf8'
  SQL (0.5ms)   SET SQL_AUTO_IS_NULL=0
  User Columns (16.2ms)   SHOW FIELDS FROM `users`
OpenIdAuthentication.store is nil. Using in-memory store.

Processing UserSessionsController#create (for 127.0.0.1 at 2010-03-29 02:30:09) [POST]
  Parameters: {"user_session"=>{"remember_me"=>"true"}, "method"=>:get, "authenticity_token"=>"<my token was here>", "action"=>"create", "openid_identifier"=>"https://www.google.com/accounts/o8/id", "controller"=>"user_sessions"}
  SQL (2.4ms)   SHOW TABLES
  SQL (14.0ms)   SHOW TABLES
  Permission Load (0.8ms)   SELECT * FROM `permissions` WHERE (name = 'Admin') LIMIT 1
  Permission Load (12.7ms)   SELECT * FROM `permissions` WHERE (name = 'Edit Tutorials') LIMIT 1
  Permission Load (1.2ms)   SELECT * FROM `permissions` WHERE (name = 'Edit Blog') LIMIT 1
  Permission Load (5.8ms)   SELECT * FROM `permissions` WHERE (name = 'Delete Comments') LIMIT 1
  Permission Load (2.9ms)   SELECT * FROM `permissions` WHERE (name = 'Browse Stats') LIMIT 1
  Permission Load (1.3ms)   SELECT * FROM `permissions` WHERE (name = 'Full Users Access') LIMIT 1
  Permission Load (5.0ms)   SELECT * FROM `permissions` 
  Permission Columns (7.6ms)   SHOW FIELDS FROM `permissions`
  UserGroup Load (0.7ms)   SELECT * FROM `user_groups` WHERE (name = 'Administrators') LIMIT 1
  UserGroup Columns (6.4ms)   SHOW FIELDS FROM `user_groups`
  permissions_user_groups Columns (4.5ms)   SHOW FIELDS FROM `permissions_user_groups`
  Permission Load (6.1ms)   SELECT * FROM `permissions` INNER JOIN `permissions_user_groups` ON `permissions`.id = `permissions_user_groups`.permission_id WHERE (`permissions_user_groups`.user_group_id = 1 ) 
Completed in 3258ms (View: 14, DB: 89) | 401 Unauthorized [http://localhost/user_session]
WARNING: making https request to https://www.google.com/accounts/o8/id without verifying server certificate; no CA path was specified.
WARNING: making https request to https://www.google.com/accounts/o8/ud without verifying server certificate; no CA path was specified.
Generated checkid_setup request to https://www.google.com/accounts/o8/ud with assocication <my token was here>
=> Requiring Lockdown rules engine: /home/gleb/projects/iRequest/iRequest-Web/lib/lockdown/init.rb 

  SQL (0.4ms)   SET NAMES 'utf8'
  SQL (0.8ms)   SET SQL_AUTO_IS_NULL=0
  User Columns (8.2ms)   SHOW FIELDS FROM `users`
OpenIdAuthentication.store is nil. Using in-memory store.
Error attempting to use stored discovery information: OpenID::TypeURIMismatch
Attempting discovery to verify endpoint
Performing discovery on https://www.google.com/accounts/o8/id?id=<my token was here>
WARNING: making https request to https://www.google.com/accounts/o8/id?id=<my token was here> without verifying server certificate; no CA path was specified.
Using 'check_authentication' with https://www.google.com/accounts/o8/ud
WARNING: making https request to https://www.google.com/accounts/o8/ud without verifying server certificate; no CA path was specified.

Processing UserSessionsController#create (for 127.0.0.1 at 2010-03-29 02:30:24) [POST]
  Parameters: {"remember_me"=>"true", "method"=>:get, "action"=>"create", "for_session"=>"1", "controller"=>"user_sessions", "locale"=>"en"}
  SQL (1.2ms)   SHOW TABLES
  SQL (0.9ms)   SHOW TABLES
  Permission Load (1.0ms)   SELECT * FROM `permissions` WHERE (name = 'Admin') LIMIT 1
  Permission Load (2.1ms)   SELECT * FROM `permissions` WHERE (name = 'Edit Tutorials') LIMIT 1
  Permission Load (3.0ms)   SELECT * FROM `permissions` WHERE (name = 'Edit Blog') LIMIT 1
  Permission Load (0.5ms)   SELECT * FROM `permissions` WHERE (name = 'Delete Comments') LIMIT 1
  Permission Load (1.0ms)   SELECT * FROM `permissions` WHERE (name = 'Browse Stats') LIMIT 1
  Permission Load (8.1ms)   SELECT * FROM `permissions` WHERE (name = 'Full Users Access') LIMIT 1
  Permission Load (0.7ms)   SELECT * FROM `permissions` 
  Permission Columns (3.6ms)   SHOW FIELDS FROM `permissions`
  UserGroup Load (0.5ms)   SELECT * FROM `user_groups` WHERE (name = 'Administrators') LIMIT 1
  UserGroup Columns (3.6ms)   SHOW FIELDS FROM `user_groups`
  permissions_user_groups Columns (2.9ms)   SHOW FIELDS FROM `permissions_user_groups`
  Permission Load (0.5ms)   SELECT * FROM `permissions` INNER JOIN `permissions_user_groups` ON `permissions`.id = `permissions_user_groups`.permission_id WHERE (`permissions_user_groups`.user_group_id = 1 ) 
  User Load (3.9ms)   SELECT * FROM `users` WHERE (`users`.`openid_identifier` = 'https://www.google.com/accounts/o8/id?id=<my token was here>') LIMIT 1
  SQL (0.5ms)   BEGIN
  User Update (1.9ms)   UPDATE `users` SET `updated_at` = '2010-03-29 00:30:25', `perishable_token` = '10Auups_e5yxUB5Prw8f', `last_login_at` = '2010-03-28 21:55:00', `current_login_at` = '2010-03-29 00:30:25', `login_count` = 6, `last_request_at` = '2010-03-29 00:30:25' WHERE `id` = 7
[paperclip] Saving attachments.
  SQL (4.7ms)   COMMIT
Redirected to http://localhost:3000/?locale=en
  user_groups_users Columns (3.3ms)   SHOW FIELDS FROM `user_groups_users`
  UserGroup Load (0.8ms)   SELECT * FROM `user_groups` INNER JOIN `user_groups_users` ON `user_groups`.id = `user_groups_users`.user_group_id WHERE (`user_groups_users`.user_id = 7 ) 
Completed in 1019ms (DB: 54) | 302 Found [http://localhost/user_session?remember_me=true&for_session=1&locale=en]
=> Requiring Lockdown rules engine: /home/gleb/projects/iRequest/iRequest-Web/lib/lockdown/init.rb 

  SQL (0.7ms)   SET NAMES 'utf8'
  SQL (0.4ms)   SET SQL_AUTO_IS_NULL=0
  User Columns (8.2ms)   SHOW FIELDS FROM `users`
OpenIdAuthentication.store is nil. Using in-memory store.

Processing HomeController#index (for 127.0.0.1 at 2010-03-29 02:30:28) [GET]
  Parameters: {"action"=>"index", "controller"=>"home", "locale"=>"en"}
  SQL (1.9ms)   SHOW TABLES
  SQL (1.1ms)   SHOW TABLES
  Permission Load (1.2ms)   SELECT * FROM `permissions` WHERE (name = 'Admin') LIMIT 1
  Permission Load (3.3ms)   SELECT * FROM `permissions` WHERE (name = 'Edit Tutorials') LIMIT 1
  Permission Load (1.0ms)   SELECT * FROM `permissions` WHERE (name = 'Edit Blog') LIMIT 1
  Permission Load (1.1ms)   SELECT * FROM `permissions` WHERE (name = 'Delete Comments') LIMIT 1
  Permission Load (1.1ms)   SELECT * FROM `permissions` WHERE (name = 'Browse Stats') LIMIT 1
  Permission Load (1.4ms)   SELECT * FROM `permissions` WHERE (name = 'Full Users Access') LIMIT 1
  Permission Load (1.3ms)   SELECT * FROM `permissions` 
  Permission Columns (3.2ms)   SHOW FIELDS FROM `permissions`
  UserGroup Load (0.6ms)   SELECT * FROM `user_groups` WHERE (name = 'Administrators') LIMIT 1
  UserGroup Columns (5.3ms)   SHOW FIELDS FROM `user_groups`
  permissions_user_groups Columns (2.1ms)   SHOW FIELDS FROM `permissions_user_groups`
  Permission Load (0.5ms)   SELECT * FROM `permissions` INNER JOIN `permissions_user_groups` ON `permissions`.id = `permissions_user_groups`.permission_id WHERE (`permissions_user_groups`.user_group_id = 1 ) 
  User Load (1.1ms)   SELECT * FROM `users` WHERE (`users`.`id` = '7') LIMIT 1
  SQL (0.7ms)   BEGIN
  User Update (1.0ms)   UPDATE `users` SET `updated_at` = '2010-03-29 00:30:29', `perishable_token` = 'OMv44uHILYST19z76SeM', `last_request_at` = '2010-03-29 00:30:29' WHERE `id` = 7
[paperclip] Saving attachments.
  SQL (3.7ms)   COMMIT
  user_groups_users Columns (2.4ms)   SHOW FIELDS FROM `user_groups_users`
  UserGroup Load (0.7ms)   SELECT * FROM `user_groups` INNER JOIN `user_groups_users` ON `user_groups`.id = `user_groups_users`.user_group_id WHERE (`user_groups_users`.user_id = 7 ) 
  Post Load (0.9ms)   SELECT id, title, created_at FROM `posts` ORDER BY created_at DESC LIMIT 3
Rendering template within layouts/application
Rendering home/index
  Post Columns (2.8ms)   SHOW FIELDS FROM `posts`
Rendered shared/_menu (7.8ms)
Rendered shared/_dj_select (4.7ms)
Rendered shared/_footer_menu (43.2ms)
Completed in 1278ms (View: 176, DB: 48) | 200 OK [http://localhost/?locale=en]
</code></pre>

What could it possibly mean?
P.S.: @mreinsch, thank you for this amazing fork!

**Comment by mreinsch** [comment]
I don't have any issues using http://www.myopenid.com/ as OpenID provider in a production environment. Does this only happen for you using Google?

**Comment by glebm** [comment]
I have this issue with all the providers. I am currently suspecting the Lockdown gem.

However, what do these lines from the log mean:
    Error attempting to use stored discovery information: OpenID::TypeURIMismatch
    Attempting discovery to verify endpoint
    Performing discovery on https://www.google.com/accounts/o8/id?id=
    WARNING: making https request to https://www.google.com/accounts/o8/id?id= without verifying server certificate; no CA path was specified.
    Using 'check_authentication' with https://www.google.com/accounts/o8/ud
    WARNING: making https request to https://www.google.com/accounts/o8/ud without verifying server certificate; no CA path was specified.

Also, the livejournal authentication fails like this:
1 error prohibited this user session from being saved

There were problems with the following fields:
OpenID verification failed

**Comment by mreinsch** [comment]
I actually don't think this is an issue in the authlogic plugin itself. 
Could you try reproducing this issue with using only the rails openid authentication plugin (http://github.com/rails/open_id_authentication) and/or the rack openid plugin (http://github.com/josh/rack-openid)? That would help a lot to further pin down the issue.

**Comment by glebm** [comment]
I found the problem.
There are 2 bugs in Rack FCGI:
1. Rack FCGI clears (sets to nil) PATH_INFO if it's empty
   I posted a ticked to the guy who wrote rack-openid and he commited a workaround for it.
2. Rack FCGI blows up if we write 401 Unauthorized to the header.
   Unfortunately, I haven't come up with a workaround for it yet.

On the bright side, this bug forced me to change my hosting provider (I'm with heroku (+ S3 for files) for now -- it has its own problems as well, but still better than Bluehost for Rails)

**Comment by mreinsch** [comment]
Ok, great you got that resolved. I'm usually using mongrel or passenger, which explains why this issue doesn't show up for me.
Cheers!

**Comment by professor** [comment]
I'm in the process of integrating open-id in rails with Google Apps user accounts. The way I removed the "WARNING: making https request to https://www.google.com/accounts/o8/ud without verifying server certificate; no CA path was specified."

a) In your config/environment.rb file add the line
OpenID.fetcher.ca_file = "#{Rails.root}/config/ca-bundle.crt"
b) You'll need to get a ca-bundle.crt file. You should add in certificate authorities that you trust. If you are in a hurry, you can use the one in the ruby-openid-apps-discovery gem. Unpack it and find it in the lib directory. I copied mine to my application's config directory.

See this blog post for more details:
http://toddsedano.blogspot.com/2010/05/integrating-openid-google-apps-and-ruby.html
