### ISSUE TITLE
PGError: ERROR:  invalid byte sequence for encoding

### ISSUE THREAD

**Issue by jeena** [mreinsch/authlogic_openid#3]
When I try to create a new user I get this error:

```
ActiveRecord::StatementInvalid (PGError: ERROR:  invalid byte sequence for encoding "UTF8": 0xe77cf0
HINT:  This error can also happen if the byte sequence does not match the encoding expected by the server, which is controlled by "client_encoding".
: INSERT INTO "open_id_authentication_associations" ("issued", "lifetime", "handle", "assoc_type", "server_url", "secret") VALUES(1272315458, 1209610, E'{HMAC-SHA1}{4bd2f102}{tEYFKQ==}', E'HMAC-SHA1', E'http://www.myopenid.com/server', E'ÁmÉ{é*)¿#4±›Ä''îÚÊú') RETURNING "id"):
```

And I have no idea how to fix it. I'm using Postgres 8.4, Rails 2.3.5 and Ruby 1.9. Any suggestions?

**Comment by mreinsch** [comment]
I think you are using the old version of the rails openid_authentication plugin. This version won't work with this fork of the authlogic_openid plugin. While this doesn't solve the actual issue that "secret" seems to be a binary value and not a UTF-8 string, the new version of the rails openid_authentication plugin doesn't use this table anymore.

**Comment by jeena** [comment]
Ah ok, very cool, but I'm so confused which version to use and how to install it, could you give me a url on how to install it today? I seem to be lost in all the different versions on different pages on the internet.

**Comment by mreinsch** [comment]
the readme contains the correct url: git://github.com/rails/open_id_authentication.git

**Comment by jeena** [comment]
Ok thanks, I will try that.

**Comment by jeena** [comment]
Hm, I am trying really hard but I just get the error: "Openid identifier had the following error: OpenID verification failed" but don't know how to solve it.
